image: archlinux
packages:
  - go
sources:
  - https://git.sr.ht/~klahr/quadrate
tasks:
  - build: |
      cd quadrate
      go mod download
      make
      sudo make install
  - test: |
      cd quadrate
      quadc --run ./tests/test_instructions.qd

