image: alpine/edge

packages:
  - bash
  - clang
  - clang-dev
  - clang-extra-tools
  - compiler-rt
  - llvm-dev
  - meson
  - musl-dev
  - nodejs
  - npm
  - openssl-dev
  - pkgconf
  - readline-dev
  - sqlite-dev
  - zlib-dev

sources:
  - https://git.sr.ht/~klahr/quadrate
  - https://git.sr.ht/~klahr/qdlog
  - https://git.sr.ht/~klahr/qdcompress
  - https://git.sr.ht/~klahr/qdtls
  - https://git.sr.ht/~klahr/qdhttp
  - https://git.sr.ht/~klahr/qdsqlite
  - https://git.sr.ht/~klahr/qdjson
  - https://git.sr.ht/~klahr/qdregex
  - https://git.sr.ht/~klahr/qdcrypto

tasks:
  - install_tree_sitter: |
      sudo npm install -g tree-sitter-cli
  - format: |
      cd quadrate
      make format
      git diff --exit-code
  - build: |
      cd quadrate
      make release
  - test: |
      cd quadrate
      make tests
  - dist: |
      cd quadrate
      if git describe --exact-match HEAD 2>/dev/null; then
        make dist
      else
        echo "Not a tagged commit, skipping dist"
      fi

triggers:
  - action: email
    condition: failure
    to: klahr@r8.rs
