image: archlinux

packages:
  - clang
  - llvm
  - meson
  - nodejs
  - openssl
  - tree-sitter-cli
  - valgrind

sources:
  - git://git@git.sr.ht:~klahr/quadrate

tasks:
  - build: |
      cd quadrate
      make release
  - test: |
      cd quadrate
      make tests
  - test_optimized: |
      cd quadrate
      bash tests/run_tests.sh optimized -O2
      bash tests/run_tests.sh optimized -O3
  - valgrind: |
      cd quadrate
      export DEBUGINFOD_URLS="https://debuginfod.archlinux.org"
      make valgrind

triggers:
  - action: email
    condition: failure
    to: klahr@r8.rs
