image: archlinux

packages:
  - clang
  - llvm
  - meson
  - openssl
  - pkgconf
  - python
  - sqlite
  - zlib

sources:
  - https://git.sr.ht/~klahr/quadrate
  - https://git.sr.ht/~klahr/qdcompress
  - https://git.sr.ht/~klahr/qdtls
  - https://git.sr.ht/~klahr/qdhttp
  - https://git.sr.ht/~klahr/qdsqlite
  - https://git.sr.ht/~klahr/qdjson

tasks:
  - format: |
      cd quadrate
      make format
      git diff --exit-code
  - build: |
      cd quadrate
      make release
  - fmtcheck: |
      cd quadrate
      make fmtcheck
  - docscheck: |
      cd quadrate
      make docscheck
  - test: |
      cd quadrate
      make tests
  - dist: |
      cd quadrate
      if git describe --exact-match HEAD 2>/dev/null; then
        make dist
      else
        echo "Not a tagged commit, skipping dist"
      fi

triggers:
  - action: email
    condition: failure
    to: klahr@r8.rs
