image: archlinux

packages:
  - clang
  - llvm
  - meson
  - nodejs
  - openssl
  - pkgconf
  - sqlite
  - tree-sitter-cli
  - valgrind
  - zlib

sources:
  - https://git.sr.ht/~klahr/quadrate
  - https://git.sr.ht/~klahr/qdlog
  - https://git.sr.ht/~klahr/qdcompress
  - https://git.sr.ht/~klahr/qdtls
  - https://git.sr.ht/~klahr/qdhttp
  - https://git.sr.ht/~klahr/qdsqlite
  - https://git.sr.ht/~klahr/qdjson
  - https://git.sr.ht/~klahr/qdregex
  - https://git.sr.ht/~klahr/qdcrypto

tasks:
  - format: |
      cd quadrate
      make format
      git diff --exit-code
  - build: |
      cd quadrate
      make release
  - test: |
      cd quadrate
      make tests
  - valgrind: |
      cd quadrate
      export DEBUGINFOD_URLS="https://debuginfod.archlinux.org"
      make valgrind
  - dist: |
      cd quadrate
      if git describe --exact-match HEAD 2>/dev/null; then
        make dist
      else
        echo "Not a tagged commit, skipping dist"
      fi

triggers:
  - action: email
    condition: failure
    to: klahr@r8.rs
