image: archlinux
packages:
  - clang
  - cmake
  - meson
  - nodejs
  - tree-sitter-cli
  - valgrind
sources:
  - https://git.sr.ht/~klahr/quadrate
  - https://git.sr.ht/~klahr/libu8t
  - https://git.sr.ht/~klahr/unit-check
tasks:
  - setup_unitcheck: |
      cd unit-check
      cmake -S . -B build
      cmake --build build --config Release
      sudo cmake --install build
  - setup_u8t: |
      cd libu8t
      cmake -S . -B build
      cmake --build build --config Release
      sudo cmake --install build
  - build: |
      cd quadrate
      make release
  - test: |
      cd quadrate
      make tests
  - valgrind: |
      cd quadrate
      export DEBUGINFOD_URLS="https://debuginfod.archlinux.org"
      make valgrind
triggers:
  - action: email
    condition: failure
    to: klahr@r8.rs
