image: debian/testing

secrets:
  - ea8ca0d9-1859-4db5-bb99-8f12baf60b59

packages:
  - clang
  - clang-format
  - libclang-rt-dev
  - libsqlite3-dev
  - libssl-dev
  - llvm-dev
  - meson
  - nodejs
  - npm
  - pkg-config
  - valgrind
  - zlib1g-dev

sources:
  - git+ssh://git@git.sr.ht/~klahr/quadrate
  - https://git.sr.ht/~klahr/qdlog
  - https://git.sr.ht/~klahr/qdcompress
  - https://git.sr.ht/~klahr/qdtls
  - https://git.sr.ht/~klahr/qdhttp
  - https://git.sr.ht/~klahr/qdsqlite
  - https://git.sr.ht/~klahr/qdjson
  - https://git.sr.ht/~klahr/qdregex
  - https://git.sr.ht/~klahr/qdcrypto

environment:
  GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"

artifacts:
  - quadrate/quadrate-*.tar.gz

tasks:
  - install_tree_sitter: |
      sudo npm install -g tree-sitter-cli
  - format: |
      cd quadrate
      make format
      git diff --exit-code
  - build: |
      cd quadrate
      make release
  - test: |
      cd quadrate
      make tests
  - valgrind: |
      cd quadrate
      make valgrind
  - dist: |
      cd quadrate
      if git describe --exact-match HEAD 2>/dev/null; then
        make dist
      else
        echo "Not a tagged commit, skipping dist"
      fi

triggers:
  - action: email
    condition: failure
    to: klahr@r8.rs
