image: debian/testing

packages:
  - clang
  - llvm-dev
  - meson
  - nodejs
  - npm
  - valgrind

sources:
  - git://git@git.sr.ht:~klahr/quadrate

tasks:
  - install_tree_sitter: |
      sudo npm install -g tree-sitter-cli
  - build: |
      cd quadrate
      make release
  - test: |
      cd quadrate
      make tests
  - test_optimized: |
      cd quadrate
      bash tests/run_tests.sh optimized -O2
      bash tests/run_tests.sh optimized -O3
  - valgrind: |
      cd quadrate
      make valgrind

triggers:
  - action: email
    condition: failure
    to: klahr@r8.rs
