image: debian/testing

secrets:
  - ea8ca0d9-1859-4db5-bb99-8f12baf60b59

packages:
  - clang
  - libclang-rt-dev
  - libsqlite3-dev
  - libssl-dev
  - llvm-dev
  - meson
  - nodejs
  - npm
  - pkg-config
  - valgrind
  - zlib1g-dev

sources:
  - git+ssh://git@git.sr.ht/~klahr/quadrate
  - https://github.com/quadrate-language/hof
  - https://github.com/quadrate-language/log
  - https://github.com/quadrate-language/compress
  - https://github.com/quadrate-language/tls
  - https://github.com/quadrate-language/http
  - https://github.com/quadrate-language/sqlite
  - https://github.com/quadrate-language/json
  - https://github.com/quadrate-language/regex
  - https://github.com/quadrate-language/crypto

environment:
  GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"

tasks:
  - install_tree_sitter: |
      sudo npm install -g tree-sitter-cli
  - build: |
      cd quadrate
      make release
  - test: |
      cd quadrate
      make tests
  - valgrind: |
      cd quadrate
      make valgrind

triggers:
  - action: email
    condition: failure
    to: klahr@r8.rs
