image: freebsd/current

packages:
  - llvm
  - meson
  - ninja
  - pkgconf
  - node
  - npm
  - tree-sitter
  - valgrind
  - python3

sources:
  - git://git@git.sr.ht:~klahr/quadrate

environment:
  IGNORE_OSVERSION: yes

tasks:
  - build: |
      cd quadrate
      make release
      echo "Build completed successfully"

triggers:
  - action: email
    condition: failure
    to: klahr@r8.rs
