subdir('version')
subdir('qc')
subdir('qdrt')
subdir('llvmgen')
subdir('qd')
# qdbits is now pure Quadrate (no C library needed)
subdir('qdfmt')
subdir('qdio')
subdir('qdmath')
subdir('qdmem')
subdir('qdnet')
subdir('qdtls')
subdir('qdhttp')
subdir('qdos')
subdir('qdsignal')
subdir('qdstr')
subdir('qdstrconv')
subdir('qdtesting')
subdir('qdtime')
subdir('qdthread')
subdir('qdcompress')
subdir('qdsqlite')
subdir('qdlog')
