subdir('bmi')
subdir('dc')
subdir('defer')
subdir('donut')
subdir('embed')
subdir('errors')
subdir('ffi')
subdir('fibonacci')
subdir('hello-world')
subdir('hello-world-c')
subdir('modules')
subdir('rest-api')
subdir('sha256sum')
subdir('sierpinski')
subdir('signal-catcher')
subdir('stars')
subdir('structs')
subdir('threading')
subdir('web-server')
