subdir('bf')
subdir('bmi')
subdir('dc')
subdir('defer')
subdir('donut')
subdir('embed')
subdir('errors')
subdir('ffi')
subdir('fibonacci')
subdir('hello-world')
subdir('hello-world-c')
subdir('hof')
subdir('lambdas')
subdir('links-api')
subdir('modules')
subdir('raytracer')
subdir('rocket')
subdir('sha256sum')
subdir('sierpinski')
subdir('signal-catcher')
subdir('stars')
subdir('structs')
subdir('tak')
subdir('threading')
